### PR TITLE
Clean out non-string option values before use

### LINKED ISSUE #6: Error when used as command line argument
``` sh
browserify ./src/app.js -o ./dist/bundle.js -t [ pkgify --packages [ --foo ./src/foo.js ] ]
```

Trying to wire up `pkgify` on the commandline like above fails with a:

```
TypeError: Object  has no method 'charAt' (while pkgify was processing ...
```

Because browserify uses https://github.com/substack/subarg there is an `_: [ ]` property in the options that holds the list of non-option arguments provided. That blows up when the array is assumed to be a string and passed to `path.normalize`.

See: https://github.com/substack/node-browserify#btransformtr-opts

### PR DESCRIPTION
**Pull request by olizilla**
Required to let pkgify work as a commandline provided transform...
Fixes #6

### CODE REVIEW

**Comment by olizilla** [comment]
:sparkles::saxophone::camel: 
I'll use moar :bug: emoji in future commits.

**Comment by oliverwoodings** [comment]
:+1: Cheers! I'll deploy asap

**Comment by olizilla** [comment]
:zap: bump :zap:

**Comment by oliverwoodings** [comment]
Sorry, I've been away for the last week. Deploying now

**Comment by oliverwoodings** [comment]
Published as 1.0.2

**Comment by olizilla** [comment]
@oliverwoodings super rad. Sorry for pestering, I was working on a demo of browserify demo for a client that uses `pkgify` magic: https://github.com/tableflip/i18n-browserify

**Pull request merged**
